### ISSUE TITLE
Bodymovin json got cut off in a square frame

### ISSUE THREAD

**Issue by cjinghong** [airbnb/lottie#117] opened 2020-02-25 10:30 UTC
I've created a pie-like shape, and used the camera to pan around it. After exporting to the json data using the bodymovin plugin, and upon viewing it in the preview, I noticed that the animation is being cut off somehow. 

Here's how the animation looks when exported to .mov compared to the one exported using bodymovin.

**Exported to .mov**
![Exported to mov](https://user-images.githubusercontent.com/11567740/75238610-44733f00-57fc-11ea-8834-3dfdd37f0871.gif)

**Exported to .json using bodymovin**
![bodymovin](https://user-images.githubusercontent.com/11567740/75238954-cb281c00-57fc-11ea-8ef1-51b7ae8099da.gif)

**Edit:**
The original .aep file
[colorwheel.aep.zip](https://github.com/airbnb/lottie/files/4249531/colorwheel.aep.zip)

**Comment by bodymovin** [comment] 2020-02-25 10:44
Hi can you share the .aep?
If you are using track masks with strokes you might need to add a transparent rectangle behind so the stroke gets fully masked

**Comment by cjinghong** [comment] 2020-02-25 10:47
@bodymovin I've edited the original comment to include the .aep file

**Comment by bodymovin** [comment] 2020-02-25 11:09
The problem is similar to track matte masks.
I've attached an example with one layer, `Step 1`, on how to solve it. If you replicate it in all, it should work fine.
[original.zip](https://github.com/airbnb/lottie/files/4249651/original.zip)

**Comment by cjinghong** [comment] 2020-02-26 02:37
@bodymovin Thanks for your help. I'm able to duplicate what you did and it is able to export the json, and previewing it in the bodymovin extension works fine. However when I tried to use it in lottie-web I'm getting an empty animation. I tried uploading it to lottiefiles.com to preview, and also getting an empty animation.

[https://lottiefiles.com/share/EsALgX](https://lottiefiles.com/share/EsALgX)

Here's the exported data.json:
[data.json.zip](https://github.com/airbnb/lottie/files/4253144/data.json.zip)

**Comment by bodymovin** [comment] 2020-02-26 03:08
Since you are using a camera, you will need to set the renderer as html instead of svg.
Having said that, it seems you are not using depth on your animation so I would suggest that you do the animation without a camera and 3d layers so you can use the regular svg rendere.

**Comment by gpeal** [comment] 2020-10-26 05:02
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

**Closed by gpeal** 2020-10-26 05:02 UTC
