### ISSUE TITLE
After Effects layer transform scale property not working properly with stroke caps in Safari

### ISSUE THREAD

**Issue by designbywillj** [airbnb/lottie#113] opened 2020-02-16 23:42 UTC
When testing in Safari, the layer transform scale property in After Effects is not affecting the end caps of the stroke like it does in After Effects and any other browser. The scale, in this case, is supposed to stretch out the shape layer to give a shaper angle to the end cap of the strokes.

https://lottiefiles.com/share/1yyS4K

What it's supposed to look like: 

![image](https://user-images.githubusercontent.com/37247445/74615075-f31fcd00-50e2-11ea-859e-cf5b64280cd2.png)

What it looks like on Safari: 

![image](https://user-images.githubusercontent.com/37247445/74615085-10549b80-50e3-11ea-9ad7-af55974b0eec.png)

**Comment by bodymovin** [comment] 2020-02-18 00:37
Hi, can you share the .aep?

**Comment by designbywillj** [comment] 2020-02-23 03:37
[VBI_Splash.zip](https://github.com/airbnb/lottie/files/4240575/VBI_Splash.zip)

**Comment by bodymovin** [comment] 2020-02-23 23:23
Hi, I just tried it in Safari and it seems to work fine.
What os and safari version are you seeing this behavior?

**Comment by designbywillj** [comment] 2020-02-23 23:57
iOS 13.3.1 (latest) and latest Safari version

**Comment by bodymovin** [comment] 2020-02-24 00:00
Does it look like that on the last frame or is it during the animation?

**Comment by designbywillj** [comment] 2020-02-24 00:05
During the entire animation.
https://cdn.discordapp.com/attachments/651508825509199893/678702921117990932/video0.mp4

I have a layer transform on the layers that stretches a square into more of that diamond shape you see in the end. That's how I get the stoke's end caps to be angled instead of being perfectly squared off if that makes sense. I just don't understand how it works in every browser except for iOS Safari

**Comment by bodymovin** [comment] 2020-03-01 15:18
Hi, it seems that ios safari is not rendering scaled trimmed strokes correctly.
There is not much I can do about it.
Can you think of another way to achieve the same effect? Perhaps using fills instead of strokes?

**Comment by designbywillj** [comment] 2020-03-01 19:13
Yeah, I can probably come up with a solution using just fills, but that will probably take a bit of time since using trim paths for this case is extremely easy. I would honestly consider this a bug for lottie-web and see if there can be a solution for a near-future update. If it's working in every other browser, even IE, then it's a bug with lottie-web

**Comment by bodymovin** [comment] 2020-03-01 20:51
I understand, but lottie-web relies on the svg implementation of every browser. If it has render glitches there is very little that I can do.
In this case I think the problem is masking the external part of a stroke.
Perhaps you can resize the rectangle and the stroke width so you don't need any masks?

**Comment by gpeal** [comment] 2020-10-26 05:00
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.

**Closed by gpeal** 2020-10-26 05:00 UTC
